### ISSUE TITLE
노드 오류

### ISSUE THREAD

**Issue by galdock** [gdl-blue/kakaotalk-on-discord-2#1]
readme.md 파일의 지시사항을 따라한 다음 node index.js를 쳤으나, 파일이 누락되었다고 떴고, 해당 파일을 노드카카오 깃허브 등에서 다운받은 파일로 채웠으나, 다른 오류가 발생했습니다.
아래는 해당 오류 전문입니다.
        class BaseBoardClient extends api.SessionWebClient {
                                          ^

TypeError: Cannot read properties of undefined (reading 'SessionWebClient')
    at G:\discordkakao\index.js:131:36
    at Object.<anonymous> (G:\discordkakao\index.js:299:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_ma
in:81:12)
    at node:internal/main/run_main_module:22:47

**Comment by gdl-blue** [comment]
NodeKakao v4.4나 v4.5, Node.js v12.x~v16.x 버전을 써보십시오

그리고 카카오톡 영구 제한 당하실 가능성이 있으므로 안 쓰시는 것을 권장합니다(나중에 앱 데이타베이스를 읽어오는 방식으로 다시 만들까 합니다)

**Comment by cusani** [comment]
현재 9.2.1 버전이용중이신데. 10일날 9.5.0 최소버전으로 업데이트 공지가 있네요. 혹시 해결방법을 아시는지요? 버전만 올려서는 답없는거같은데. 이전 노카깃헙에서 활동하신것보고 검색하던차에 찾아보았네요.

**Comment by gdl-blue** [comment]
버전만 올려도 될 것 같습니다만, 이것을 돌리면 정지당할 가능성이 있으므로 하지 않으시는 것을 추천합니다
